app:
  title: IA-OPS Developer Portal
  baseUrl: http://localhost:3002

organization:
  name: IA-OPS

backend:
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: false

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Domain, Group, User]
  
  locations:
    - type: file
      target: ../../catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Template, Domain, Group, User]

auth:
  providers:
    guest: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
