#!/bin/bash

echo "🔧 CONFIGURACIÓN DE GITHUB ACTIONS PARA BACKSTAGE"
echo "================================================="

echo ""
echo "📋 RESUMEN DE LA IMPLEMENTACIÓN:"
echo "==============================="
echo "✅ Plugin de GitHub Actions ya está instalado en el frontend"
echo "✅ Configuración de integración con GitHub está lista"
echo "✅ Scripts de diagnóstico y prueba creados"
echo "✅ Componente de prueba agregado al catálogo"
echo "✅ Script de inicio con variables de entorno configurado"

echo ""
echo "🔑 ACCIÓN REQUERIDA - CONFIGURAR TOKEN DE GITHUB:"
echo "================================================"
echo "1. Ve a GitHub.com → Settings → Developer settings → Personal access tokens → Tokens (classic)"
echo "2. Clic en 'Generate new token (classic)'"
echo "3. Nombre: 'Backstage Integration'"
echo "4. Selecciona estos permisos:"
echo "   ☐ repo (Full control of private repositories)"
echo "   ☐ workflow (Update GitHub Action workflows)"
echo "   ☐ read:org (Read org and team membership)"
echo "   ☐ read:user (Read user profile data)"
echo "   ☐ user:email (Access user email addresses)"
echo "5. Copia el token generado (empieza con 'ghp_')"

echo ""
echo "6. Edita el archivo de configuración:"
echo "   nano ../../.env"
echo ""
echo "7. Reemplaza esta línea:"
echo "   GITHUB_TOKEN=ghp_REPLACE_WITH_YOUR_ACTUAL_TOKEN"
echo "   Con:"
echo "   GITHUB_TOKEN=tu_token_real_aqui"

echo ""
echo "🧪 PRUEBAS DISPONIBLES:"
echo "======================"
echo "• Probar token de GitHub:"
echo "  ./test-github-token.sh"
echo ""
echo "• Diagnóstico completo:"
echo "  ./diagnose-github-actions.sh"

echo ""
echo "🚀 INICIAR BACKSTAGE:"
echo "===================="
echo "Una vez configurado el token, inicia Backstage con:"
echo "  ./start-with-env.sh"

echo ""
echo "🔍 VERIFICAR GITHUB ACTIONS:"
echo "============================"
echo "1. Ve a http://localhost:3002"
echo "2. Navega a Catalog → Components"
echo "3. Busca 'test-github-actions'"
echo "4. Haz clic en el componente"
echo "5. Busca la pestaña 'GitHub Actions' (si el token está configurado correctamente)"

echo ""
echo "❌ SOLUCIÓN AL ERROR 404:"
echo "========================="
echo "El error 404 de GitHub Actions se debe a:"
echo "• Token de GitHub no configurado o inválido"
echo "• Una vez configurado el token, el error desaparecerá"

echo ""
echo "📁 ARCHIVOS CREADOS/MODIFICADOS:"
echo "==============================="
echo "• ./start-with-env.sh - Script de inicio con variables de entorno"
echo "• ./test-github-token.sh - Script para probar el token"
echo "• ./diagnose-github-actions.sh - Diagnóstico completo"
echo "• ./examples/test-component.yaml - Componente de prueba"
echo "• ./app-config.yaml - Configuración actualizada"

echo ""
echo "🎯 PRÓXIMOS PASOS:"
echo "=================="
echo "1. Configurar el token de GitHub en ../../.env"
echo "2. Ejecutar ./test-github-token.sh para verificar"
echo "3. Ejecutar ./start-with-env.sh para iniciar Backstage"
echo "4. Verificar que GitHub Actions funciona en la interfaz web"

echo ""
echo "✨ ¡Implementación completada! Solo falta configurar el token de GitHub."
