#!/bin/bash

# Script para monitorear el workflow de Docker Hub (Privado)
echo "🔒 Monitoreo del Workflow de Docker Hub (Privado)"
echo "================================================"

# Información del repositorio
REPO_OWNER="giovanemere"
REPO_NAME="ia-ops"
DOCKER_HUB_REPO="giovanemere/ia-ops-backstage-private"

echo ""
echo "📊 Información:"
echo "   Repository: $REPO_OWNER/$REPO_NAME"
echo "   Docker Hub: $DOCKER_HUB_REPO (PRIVADO)"
echo "   Workflow: docker-hub-push-private.yml"

echo ""
echo "🔗 Enlaces importantes:"
echo "   📋 GitHub Actions: https://github.com/$REPO_OWNER/$REPO_NAME/actions"
echo "   🔒 Docker Hub Push (Privado): https://github.com/$REPO_OWNER/$REPO_NAME/actions/workflows/docker-hub-push-private.yml"
echo "   🏗️ Build Backstage: https://github.com/$REPO_OWNER/$REPO_NAME/actions/workflows/backstage-build.yml"
echo "   🔒 Docker Hub Repo (Privado): https://hub.docker.com/r/$DOCKER_HUB_REPO"
echo "   🔑 GitHub Secrets: https://github.com/$REPO_OWNER/$REPO_NAME/settings/secrets/actions"

echo ""
echo "📋 Estado actual:"

# Verificar último commit
echo "🕐 Último commit:"
git log --oneline -1

echo ""
echo "🔍 Workflows que deberían activarse:"
echo "   🔒 Push to Docker Hub (Private) (docker-hub-push-private.yml)"
echo "   🏗️ Build Backstage (backstage-build.yml)"
echo "   ✅ Trunk Branch Validation (trunk-validation.yml)"

echo ""
echo "🎯 Qué buscar en el workflow 'Push to Docker Hub (Private)':"
echo "   1. ✅ Checkout code"
echo "   2. ✅ Set up Docker Buildx"
echo "   3. ✅ Login to Docker Hub (aquí puede fallar si no hay secrets)"
echo "   4. ✅ Extract metadata"
echo "   5. ✅ Build and push to Docker Hub (Private)"
echo "   6. ✅ Success notification"

echo ""
echo "🔒 Características del Repositorio Privado:"
echo "   - Solo usuarios autorizados pueden acceder"
echo "   - Requiere 'docker login' para pull"
echo "   - No aparece en búsquedas públicas"
echo "   - Mayor seguridad para código propietario"

echo ""
echo "❌ Posibles errores y soluciones:"
echo ""
echo "🔐 Error: 'Login to Docker Hub' falla"
echo "   Causa: Secrets no configurados o incorrectos"
echo "   Solución:"
echo "   1. Ve a: https://github.com/$REPO_OWNER/$REPO_NAME/settings/secrets/actions"
echo "   2. Verifica DOCKER_HUB_USERNAME = giovanemere"
echo "   3. Verifica DOCKER_HUB_TOKEN = [tu access token]"
echo ""

echo "🏗️ Error: 'Build and push' falla"
echo "   Causa: Problemas con Dockerfile.optimized"
echo "   Solución:"
echo "   1. Ejecuta: ./applications/backstage/diagnose-github-build.sh"
echo "   2. Prueba local: ./applications/backstage/simulate-github-actions-build.sh"
echo ""

echo "🔒 Error: 'Repository not found' o 'Access denied'"
echo "   Causa: Repositorio privado no existe o sin permisos"
echo "   Solución:"
echo "   1. Crear repositorio privado en Docker Hub manualmente"
echo "   2. Ve a: https://hub.docker.com/repository/create"
echo "   3. Nombre: ia-ops-backstage-private"
echo "   4. Visibilidad: Private"
echo ""

echo "🐳 Error: 'unauthorized: authentication required'"
echo "   Causa: Access token inválido o sin permisos"
echo "   Solución:"
echo "   1. Ve a: https://hub.docker.com/settings/security"
echo "   2. Crea nuevo token con permisos 'Read, Write, Delete'"
echo "   3. Actualiza DOCKER_HUB_TOKEN en GitHub secrets"

echo ""
echo "🧪 Para probar manualmente:"
echo "   # Ejecutar workflow desde GitHub"
echo "   1. Ve a: https://github.com/$REPO_OWNER/$REPO_NAME/actions/workflows/docker-hub-push-private.yml"
echo "   2. Click 'Run workflow'"
echo "   3. Selecciona 'trunk'"
echo "   4. Click 'Run workflow'"
echo ""
echo "   # Probar build local (repositorio privado)"
echo "   ./applications/backstage/push-to-docker-hub-private.sh"

echo ""
echo "🔍 Verificar resultado (repositorio privado):"
echo "   # Verificar imagen privada en Docker Hub"
echo "   ./scripts/verify-docker-hub-private.sh"
echo ""
echo "   # Pull manual (requiere autenticación)"
echo "   docker login"
echo "   docker pull $DOCKER_HUB_REPO:latest"

echo ""
echo "📱 Comandos útiles:"
echo "   # Ver workflows recientes (requiere gh cli con permisos)"
echo "   # gh run list --workflow=docker-hub-push-private.yml"
echo ""
echo "   # Ver logs de un run específico"
echo "   # gh run view [RUN_ID] --log"
echo ""
echo "   # Ejecutar workflow manualmente"
echo "   # gh workflow run docker-hub-push-private.yml"

echo ""
echo "🔒 Pasos para crear repositorio privado en Docker Hub:"
echo "   1. Ve a: https://hub.docker.com/repository/create"
echo "   2. Repository Name: ia-ops-backstage-private"
echo "   3. Visibility: Private"
echo "   4. Description: Private Backstage Developer Portal for IA-Ops Platform"
echo "   5. Click 'Create'"

echo ""
echo "🔑 Comandos para usar repositorio privado:"
echo "   # Autenticarse"
echo "   docker login"
echo ""
echo "   # Pull imagen privada"
echo "   docker pull $DOCKER_HUB_REPO:latest"
echo ""
echo "   # Ejecutar imagen"
echo "   docker run -p 7007:7007 $DOCKER_HUB_REPO:latest"

echo ""
echo "⏰ Los workflows pueden tardar 1-2 minutos en aparecer después del push."
echo "   Revisa los enlaces arriba para monitorear el progreso."

echo ""
echo "🔒 Recordatorio: Este es un repositorio PRIVADO"
echo "   - Solo usuarios autorizados pueden acceder"
echo "   - Requiere autenticación con Docker Hub"
echo "   - Mayor seguridad para tu código"

echo ""
echo "✅ Monitoreo configurado. ¡Revisa GitHub Actions para ver el progreso!"
